import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import localFont from 'next/font/local'
import SideMenu from "./_components/SideMenu/SideMenu";

const sofia = localFont({
  src: [
    { path: "../public/fonts/sofia/Sofia Pro Regular Az.woff", weight: "400", style: "normal" },
    { path: "../public/fonts/sofia/Sofia Pro Medium Az.woff", weight: "500", style: "normal" },
    { path: "../public/fonts/sofia/Sofia Pro Semi Bold Az.woff", weight: "600", style: "normal" },
    { path: "../public/fonts/sofia/Sofia Pro Bold Az.woff", weight: "700", style: "normal" },
  ],
  variable: "--font-sofia",
});

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-Commerce Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.className} ${sofia.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col text-[14px]">
        <div className='flex min-h-screen lg:h-screen overflow-hidden'>
          <SideMenu/>
          <main className='flex flex-1 min-h-0 w-full'>
            <Provider>
              {children}
            </Provider>
          </main>
        </div>
      </body>
    </html>
  );
}
